Map<String, String> cardDescription = {
  'ХВАТЬ-ХВАТЬ' : 'Discard 1 card',
  'АРТАБСТОЙЛО' : 'Discard 2 cards',
  'АРТАБСТОЙЛО1' : 'Destroy 1 unicorn',
  'ДИСКОБОМБА' : 'Sacrifice 1 card',
  'ДИСКОБОМБА1' : 'Destroy 1 card',
  'КОФЕЙНЫЙ ДЕБОШ' : 'Sacrifice 1 card',
  'РАДУЖНОЕ ЛАССО' : 'Discard 3 cards',
  'РАДУЖНОЕ ЛАССО1' : 'Steal 1 unicorn',


  'assets/1ff.png' : 'СЛЕПЯЩИЙ СВЕТ',
  'assets/3ff.png' : 'ПАНДЕЦ',
  'КОЛЮЧАЯ ПРОВОЛКА' : 'Discard 1 card',
  'МИНИ-СТОЙЛО' :  'You have more than 5 unicorns in your stall, discard',




  'ЕДИНОРОЖИЙ ЯД': 'Choose the unicorn you want to destroy',
  'БЛЕСТЯЩЕЕ ТОРНАДО1' :'Choose the card you want to take into your hand',
  'БЛЕСТЯЩЕЕ ТОРНАДО2' :'Choose which card your opponent should take into his hand',
  'ПИНОК' :'Return 1 card to hand',
  'ПИНОК1' :'Discard 1 card',
  'КЛЕВЕР-ПЕРЕВЕРТЫШ' :'Discard 3 cards and then make another move',
  'ПОЦЕЛУЙ ЛЮБВИ' :'Choose the unicorn you want to add to your stall',
  'НАГЛЫЙ ГРАБЕЖ' :'Choose the card you want to steal',
  'ОБМЕН ЕДИНОРОЖКАМИ' :'Choose the unicorn you want to exchange',
  'ОБМЕН ЕДИНОРОЖКАМИ1' :'Choose the unicorn you want to steal',
  'ДВА ПО ЦЕНЕ ОДНОГО1' : 'Choose a card to sacrifice',
  'ДВА ПО ЦЕНЕ ОДНОГО2' :'Choose 2 cards that you will destroy',
  'МИСТИЧЕСКИЙ ВОДОВОРОТ' :'Discard 1 card',
  'ЦЕЛЬСЬ!' :'Give away your bonuses/fines or take another player\'s cards?',
  'ПРИЦЕЛЬНАЯ АТАКА' :'Destroy a bonus or sacrifice a fine',
  'ЧИСТАЯ ВЫГОДА' :'Discard 1 card',


  'АВРАЛЬНЫЙ НАРВАЛ' : 'Choose the fine you want',
  'МАНЯЩИЙ НАРВАЛ' : 'You can steal 1 bonus',
  'ВЕЛИКИЙ НАРВАЛ' : 'Choose the unicorn you want',
  'НОСОРОГОРОГ' : 'Destroy 1 unicorn',
  'ЛАМАРОГ' : 'Discard 1 card',
  'ЖИРНОРОГ' : 'You cannot use TПРУ',
  'assets/8u.png' : 'ЧЕРНЫЙ БРОНЕРОГ',
  'АМЕРИРОГ' : 'Choose 1 card',
  'АКУЛОРОГ' : 'When АКУЛОРОГ in you stall you can sacrifice the card and destroy 1 unicorn',
  'КРУШЕРОГ' : 'Sacrifice 1 unicorn',
  'ОРАКУЛОРОГ' : 'Choose 1 card',
  'ИМПОЗАНТНЫЙ НАРВАЛ' : 'Choose the bonus you want',
  'БЕСЯЧИЙ КРЫЛОРОГ' : 'Discard 1 card',
  'ВОЛШЕБНЫЙ КРЫЛОРОГ' : 'Choose the spell you want',
  'НОЖЕРОГ' : 'Destroy 1 unicorn',
  'ТЕМНЫЙ АНГЕЛОРОГ' : 'Choose the unicorn you want to sacrifice',
  'ТЕМНЫЙ АНГЕЛОРОГ1' : 'Choose the unicorn you want',
  'ПОЧАТОК РОГ' : 'Discard 1 card',
  'ПАФОСНЫЙ КРЫЛОРОГ' : 'Choose the unicorn you want',
  'РУСАЛКОРОГ' : 'Return 1 card to hand',
  'assets/25u.png' : 'ФЕНИКСОРОГ',
};