Map<String, String> cardDescription = {
  'assets/1b.png' : 'ХВАТЬ-ХВАТЬ',

  'assets/4b.png' : 'АРТАБСТОЙЛО',

  'assets/7b.png' : 'ДИСКОБОМБА',

  'assets/10b.png' : 'КОФЕИНОВЫЙ ДЕБОШ',
  // 'РАДУЖНАЯ АУРА' : 'РАДУЖНАЯ АУРА',
  'assets/12b.png' : 'ПРЫГ-СКОК',
  'assets/13b.png' : 'РАДУЖНОЕ ЛАССО',
  'assets/1ff.png' : 'СЛЕПЯЩИЙ СВЕТ',
  'assets/2ff.png' : 'ОТСТОЙЛО',
  'assets/3ff.png' : 'ПАНДЕЦ',
  'assets/4ff.png' : 'КОЛЮЧАЯ ПРОВОЛОКА',
  'assets/5ff.png' : 'МИНИ-СТОЙЛО',
  'ЕДИНОРОЖИЙ ЯД': 'Choose the unicorn you want to destroy',

  'assets/4s.png' :'БЛЕСТЯЩЕЕ ТОРНАДО',

  'assets/6s.png' :'ПИНОК',

  'assets/9s.png' :'КЛЕВЕР-ПЕРЕВЕРТЫШ',

  'assets/11s.png' :'ПОЦЕЛУЙ ЛЮБВИ',
  'assets/12s.png' :'НЕЧЕСТНАЯ СДЕЛКА',
  'assets/14s.png' :'НАГЛЫЙ ГРАБЕЖ',
  'assets/15s.png' :'ОБМЕН ЕДИНОРОЖКАМИ',
  'ДВА ПО ЦЕНЕ ОДНОГО1' :'Choose a card to sacrifice',
  'ДВА ПО ЦЕНЕ ОДНОГО2' :'Choose 2 cards that you will destroy',
  'assets/19s.png' :'МИСТИЧЕСКИЙ ВОДОВОРОТ',
  'assets/20s.png' :'ВСТРЯСКА',
  'assets/21s.png' :'ЦЕЛЬС!',
  'assets/23s.png' :'ПРИЦЕЛЬНАЯ АТАКА',
  'assets/24s.png' :'ПЕРЕЗАГРУЗКА',
  'assets/25s.png' :'ЧИСТАЯ ВЫГОДА',

  'assets/1u.png' : 'АВРАЛЬНЫЙ НАРВАЛ',
  'assets/2.png' : 'МАНЯЩИЙ НАРВАЛ',
  'assets/3u.png' : 'ТОРПЕДНЫЙ НАРВАЛ',
  'assets/4u.png' : 'ВЕЛИКИЙ НАРВАЛ',
  'assets/5u.png' : 'НОСОРОГОРОГ',
  'ЛАМАРОГ' : 'Каждый игрок должен сбросить по 1 карте с руки',
  'assets/7u.png' : 'ЖИРНОРОГ',
  'assets/8u.png' : 'ЧЕРНЫЙ БРОНЕРОГ',
  'assets/9u.png' : 'АМЕРИРОГ',
  'assets/10u.png' : 'АКУЛОРОГ',
  'assets/11u.png' : 'ВОЛШЕБНЫЙ КОТОРОГ',
  'assets/12u.png' : 'КРУШЕРОГ',
  'assets/13u.png' : 'ОРАКУЛОРОГ',
  'assets/14u.png' : 'ИМПОЗАНТНЫЙ НАРВАЛ',
  'assets/15u.png' : 'ЖАДНЫЙ КРЫЛОРОГ',
  'assets/16u.png' : 'БЕСЯЧИЙ КРЫЛОРОГ',
  'assets/17u.png' : 'ВОЛШЕБНЫЙ КРЫЛОРОГ',
  'assets/18u.png' : 'НОЖЕРОГ',
  'assets/19u.png' : 'ТЕМНЫЙ АНГЕЛОРОГ',
  'assets/20u.png' : 'РУСАЛКОРОГ',
  'assets/21u.png' : 'ПОЧАТОКРОГ',
  'assets/22u.png' : 'РЕАКТИВНЫЙ КРЫЛОРОГ',
  'assets/23u.png' : 'БЕНЗОПИЛОРОГ',
  'assets/24u.png' : 'ПАФОСНЫЙ КРЫЛОРОГ',
  'assets/25u.png' : 'ФЕНИКСОРОГ',
};