// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV-fnUNU-1yLmCt9V1qVKaO9-ORGxVngo',
    appId: '1:774725142838:web:bae823282e31b92d690b97',
    messagingSenderId: '774725142838',
    projectId: 'unstable-unicorns-2a38e',
    authDomain: 'unstable-unicorns-2a38e.firebaseapp.com',
    storageBucket: 'unstable-unicorns-2a38e.appspot.com',
    databaseURL: 'https://unstable-unicorns-2a38e-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0djpYGxaefi4L6-BXm-5a0g-ijhSJMyc',
    appId: '1:774725142838:android:263171ac6b8e1fba690b97',
    messagingSenderId: '774725142838',
    projectId: 'unstable-unicorns-2a38e',
    storageBucket: 'unstable-unicorns-2a38e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtyzT8LRv5_-frCvADKLMCXxLsRQVWVIw',
    appId: '1:774725142838:ios:8574e163cb1c720f690b97',
    messagingSenderId: '774725142838',
    projectId: 'unstable-unicorns-2a38e',
    storageBucket: 'unstable-unicorns-2a38e.appspot.com',
    iosBundleId: 'com.example.unstableUnicorns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtyzT8LRv5_-frCvADKLMCXxLsRQVWVIw',
    appId: '1:774725142838:ios:8574e163cb1c720f690b97',
    messagingSenderId: '774725142838',
    projectId: 'unstable-unicorns-2a38e',
    storageBucket: 'unstable-unicorns-2a38e.appspot.com',
    iosBundleId: 'com.example.unstableUnicorns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV-fnUNU-1yLmCt9V1qVKaO9-ORGxVngo',
    appId: '1:774725142838:web:be2688c80d604d2d690b97',
    messagingSenderId: '774725142838',
    projectId: 'unstable-unicorns-2a38e',
    authDomain: 'unstable-unicorns-2a38e.firebaseapp.com',
    storageBucket: 'unstable-unicorns-2a38e.appspot.com',
  );

}